### ISSUE TITLE
Tests do not run due to missing nested dependency

### ISSUE THREAD

**Issue by Nargonath** [hapipal/hpal-debug#13]
I tried to run the test locally but I get this error when I do:

```
> hpal-debug@1.5.0 test /home/jpauthier/workspace/hpal-debug
> lab -a @hapi/code -t 100 -L -I "FinalizationRegistry,WeakRef"

Error requiring file: /home/jpauthier/workspace/hpal-debug/test/closet/repl/pal-plugins/server.js
Cannot find module 'joi'
Require stack:
- /home/jpauthier/workspace/hpal-debug/node_modules/schwifty/lib/index.js
- /home/jpauthier/workspace/hpal-debug/test/closet/repl/pal-plugins/server.js
- /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js
- /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/bin/lab
Error: Cannot find module 'joi'
Require stack:
- /home/jpauthier/workspace/hpal-debug/node_modules/schwifty/lib/index.js
- /home/jpauthier/workspace/hpal-debug/test/closet/repl/pal-plugins/server.js
- /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js
- /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/bin/lab
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/jpauthier/workspace/hpal-debug/node_modules/schwifty/lib/index.js:6:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.require.extensions.<computed> [as .js] (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/coverage.js:127:28)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/jpauthier/workspace/hpal-debug/test/closet/repl/pal-plugins/server.js:3:18)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.require.extensions.<computed> [as .js] (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/coverage.js:127:28)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js:134:13
    at Array.forEach (<anonymous>)
    at Object.internals.traverse (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js:128:15)
    at Object.exports.run (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/lib/cli.js:61:31)
    at main (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/bin/lab:56:48)
    at Object.<anonymous> (/home/jpauthier/workspace/hpal-debug/node_modules/@hapi/lab/bin/lab:60:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! Test failed.  See above for more details.
```

The problem seems to be coming from Schwifty. In the `lib/index.js` we `require('joi')` but `joi` is a `devDependency` and `@hapi/joi@16` is in the `dependencies` section. That way I guess it works when running Schwifty from the repo itself. I believe devDeps are not installed when installing a package dependency from NPM and as hpal-debug does not have joi in its dependencies but rather `joi-17` joi is nowhere to be found in the dependency tree thus it breaks when running `hpal-debug` tests.

**Comment by devinivy** [comment]
Thanks for flagging this.  With schwifty v5.4.1 published and https://github.com/hapipal/schwifty/issues/96 addressed this should now be fixed.
